### ISSUE TITLE
Build Error: The type or namespace name 'Log' does not exist in the namespace 'CGM.Communication'

### ISSUE THREAD

**Issue by emorrison1962** [cfaagaard/CGM.NET#1]
Hi! I'm excited about your project.

My name is Eric Morrison. I've been a T1D for 52 years, Windows developer for 25.
I'm hoping to leverage your work in order to extract the raw data from the 670g, as the Export function on Carelink, is no longer working for the 670.

So...I cloned the repo and am getting this error on initial build attempt:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Log' does not exist in the namespace 'CGM.Communication' (are you missing an assembly reference?)	CGM.Communication	C:\Dev\CGM.NET\.NET standard\CGM.Communication\BaseContext.cs	2	N/A

VS2017, Windows 10.

Look forward to hearing from you.
Thanks in advance!

**Comment by cfaagaard** [comment]
Hi Eric,
thanks for trying out the code. 
Have you gotten/updated all the nuget reference? I use Microsoft.Extensions.Logging for the logging.

In terms of getting raw data: I don't know how much you know about the 600-series and its protocol.
But this version are getting status-information from the "StatusResponseMessage". This message do not have all the information that I want.
So I am working on getting all the events/history, just as you would get from the carelink-csv. And may this is what you are looking for.

I expect to checkin a new version this weekend with the history.

**Comment by cfaagaard** [comment]
Nope you are right, something is wrong. Releasing a new version now. Hang on.

**Comment by cfaagaard** [comment]
I should work now. 
Just released a new version, downloaded the project-zip, and debugged the application.
And it works. 

Sorry for that. 

This version has most of the event/history code also. But it is not completely done and tested. 
I will complete it/ test it this weekend. (both on win10 and raspberry pi 3).

**Comment by cfaagaard** [comment]
Hi Eric,
if you like, you can open another issue and describe your functionality-need for getting raw data from the pump. So maybe we can put in the application also. 
Examples/ideas: 
- automated export to a csv on a OneDrive.
- new page in uwp-app with to- and from-date and button for getting csv-file for that periode.

I have been looking at using powerbi or maybe another bi-tool.(instead of carelink) Maybe the project tidepool (https://tidepool.org/ ). In the near future it will support upload of data from the Medtronic 600-series pumps (incl. 670). But as a manual proces. I want to automate this. So when my son sleeps (he is the one with T1D) his data gets uploaded to tidepool (via the raspberry pi).

(I will be offline for the rest of the day (European time) as I am travling right now :-) )

**Comment by emorrison1962** [comment]
Thanks! I'll grab it this evening.

**Comment by cfaagaard** [comment]
Can I close this issue?

**Comment by emorrison1962** [comment]
Fixed!
