### ISSUE TITLE
UI Enhancement requests

### ISSUE THREAD

**Issue by emorrison1962** [cfaagaard/CGM.NET#5]
1) Add a button to get data NOW.
2) Context menu to clear logged data.
Thanks!

**Comment by cfaagaard** [comment]
Hi,

thanks for the feedback. It is really nice knowing people are trying out the code. 

1. "Now" button
I use the toggle button (on/off) at the top. Just switch it on or off. 

2. Instead of a context menu (not that touch friendly) I have added a "delete"-icon just above the list to the right. (no "Are you sure"-confirmation)

**Comment by emorrison1962** [comment]
Thanks!
